### PR TITLE
[misc] Add prettier as a code formatter

### PR DESCRIPTION
**Pull request by joebalancio**
As the title says, this adds prettier as a code formatter. In addition it adds a few more dev dependencies (pretty-quick and husky). Pretty-quick allows formatting only on staged files. Husky exposes git hooks into package.json so that formatting can be applied when committing code.

This also formats the JS files in `/desktop-app/js`

### CODE REVIEW

**Comment by shaneharris** [comment]
Oh awesome! This is really good! Takes a lot of the pain out of it. Does it support typescript?

**Comment by joebalancio** [comment]
@shaneharris Yes, this supports Typescript and also CSS and CSS preprocessors. Check out https://prettier.io/. There's a full list towards the bottom of that page.

**Comment by joebalancio** [comment]
@shaneharris There were some merge conflicts due to me formatting some code. I've fixed them such that no current files have been formatted yet. Once merged, devs should merge master into their branches to avoid any future merge conflicts with formatted code.

**Comment by shaneharris** [comment]
oh sweet thanks for resolving those! i was going to rebase but that works too!

**Pull request merged**
