### PR TITLE
Use ADB from PATH when available

### PR DESCRIPTION
**Pull request by josephsmendoza**
this completes the first part of issue #107

### CODE REVIEW

**Comment by shaneharris** [comment]
This LGTM, @drewbaumann @srvrguy @ATechAdventurer see any issue with this?

**Comment by drewbaumann** [comment]
So if I am getting this correct the goal of this PR is to use a system available install of adb if one exists. Another PR might include preventing the download of adb by SideQuest in the event that a working system copy of adb is available. @josephsmendoza is this correct?

**Comment by shaneharris** [comment]
@drewbaumann I think this PR already does just that - he hooks into the downloaded check for ADB `isAdbDownloaded()`

**Comment by josephsmendoza** [comment]
Yes, this should make it such that when SideQuest checks for adb presence, it will use the native command (`which` on mac/linux and `where` on windows) to locate ADB and update the variable with its location before returning true. When ADB is not in PATH, the check for the proprietary ADB install now looks for `adb.exe` inside of the `platform-tools` folder, triggering an adb download if, for example, antivirus has deleted it.

**Comment by drewbaumann** [comment]
Cool. LGTM

**Comment by josephsmendoza** [comment]
Pardon, I'm quite new to git, what does that mean?

**Comment by drewbaumann** [comment]
> Pardon, I'm quite new to git, what does that mean/how does one do that?

[This is an overview of several ways to do it.](https://gist.github.com/patik/b8a9dc5cd356f9f6f980) Personally I use an interactive rebase.

That would look like:
```bash
git rebase -i origin/release-0.5.0
```
So you are rebasing against the branch you are merging into (I changed it to release-0.5.0 so we can get this change into the next planned release)
You would then basically have an interface like this: 



When you use an `f` that is giving that commit the fixup command. That will drop the commit message and roll the changes into the prior commit. Squash on the other hand combines the commit messages, but you don't want to do that in this scenario.

**Comment by josephsmendoza** [comment]
Nevermind, I figured it out.

**Comment by drewbaumann** [comment]
@josephsmendoza Awesome! Much appreciated.

**Pull request merged**
