### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by srvrguy**
This re-works packaging for the application. It moves from electron-packager to electron-builder. In the process, it also removes npm in favor of yarn, as recommended by the electron-builder project.

To build, you can now just run `yarn dist` to package for the current platform, or pass switches to build for other platforms. For example, running `yarn dist -wlm` will build the configured targets for Windows, macOS, and Linux. Output is placed in the "dist" folder. The "build" folder now contains assets needed for the packaging, mainly app icons and the window background image for the macOS dmg target.

This also moves closer to a better update notification and download system, as it generates the needed files for electron-updater.

### CODE REVIEW

**Comment by shaneharris** [comment]
this is an awesome update! if this can provide updates on all platforms it really solves that issue for me.

**Comment by drewbaumann** [comment]
I'll pull down your branch and give it a try!

**Comment by srvrguy** [comment]
Auto updates aren't currently integrated, but can be supported. There are some limitations like requiring code signing to auto-upgrade. I think upgrade notifications will work fine without, however.

Also, you can configure so that TravisCI (or any CI platform, really) can generate the build on a tag and make a release on GH. Once again, not configured here, but the possibility exists.

As long as you're using Electron as the base, this will work with Angular too.

**Comment by drewbaumann** [comment]
I just gave this a shot and it works well!

**Comment by shaneharris** [comment]
This is fantastic and indeed CI would be amazing at this point, releasing is a real pain right now. I plan on getting the angular conversion started today - this should be relatively easy as its all es6 already. Ill just try to refactor some of the classes as some of them are riddled with bad smells currently. Can we merge this at that point?

**Comment by srvrguy** [comment]
I don't see any reason that merging this couldn't wait until the conversion. However, it's basically separate from that, so it shouldn't have have any affect on the conversion either. You'd just need to switch to yarn earlier.

**Comment by shaneharris** [comment]
Yeh for sure, TBH im just delaying because releases have been flying out so quick yesterday and today. It's all very time sensitive too with Virtual Desktop doing a release at the same time etc.  I'm just being nervous about changing process and ending up stuck on something. We will get this in very soon.

**Comment by shaneharris** [comment]
Ok I have merged this in, I made a `pre-angular` branch if we need any emergency fixes in the mean time. 
I would love to get this, angular and travis ( unless there is a better option ) in before the next release. No time sensitivity though

**Comment by drewbaumann** [comment]
Circleci is nice as well

Drew Baumann
(310) 593-3133

**Pull request merged**
