### PR TITLE
guided install

### PR DESCRIPTION
**Pull request by josephsmendoza**
This is my solution to #99 and #107. The adb library used already supports the feature in #107 and seems to prefer it, all that's needed is to stop the installing of adb when it's available in $PATH. When it isn't available, I think it would be better to add it to PATH since adb is used for much more than just sideloading, but even then for many more devices than the ones supported by SideQuest. The installer I've built over [here](https://github.com/josephsmendoza/SideQuest-Installer/releases) already does this for windows, and I can build solutions for Mac and Linux as well, although they're quite redundant until SideQuest has its adb-installing code removed/disabled, which of course shouldn't happen until these installers are built. Also, I was told it should support CI. I don't really know what that is. My starting point for these installers is at the releases page. The process of updating the sidequest files in the installers can be scripted fairly easily if CI can run scripts after building.

### CODE REVIEW

**Comment by shaneharris** [comment]
Thanks for this! This should be possible to include and I think it could be great to have a proper installer for people. What would also be great is if we can also accomodate an auto update system of some sort. Indeed covering linux and mac is also a requirement but we can explore that in due time too. I'm currently looking at an angular conversion. 

BTW CI stands for Continuous integration - its automated deployments with testing usually

**Comment by josephsmendoza** [comment]
I have added the script I use for adb install/update for clarity

**Comment by josephsmendoza** [comment]
Dropping the adb via installer in favor of in-app PATH implementation, this adds a start menu shortcut and a prettier installer

**Comment by josephsmendoza** [comment]
Added a script for installing on Linux, defaults to `/opt/sidequest`, creates a `$PATH` entry and `.desktop` file

**Comment by josephsmendoza** [comment]
I've fallen short of cross-platform due to requiring mac to create a `.dmg` file, but if you haven't seen it already, there's [this thing for building electron apps on each platform with CI](https://github.com/electron-userland/electron-builder)

**Pull request closed without merging**
